name: Hourz
load: lib/application.rb
version: "1.1.1"
icon: resources/HotCocoa.icns
info_string: "Copyright © 2010 Gary S. Weaver, released under the MIT license."
resources:
  - resources/**/*.*
sources: 
  - lib/**/*.rb
